<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="Current" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <VALHEIM_INSTALL Condition="!Exists('$(VALHEIM_INSTALL)')">D:\SteamLibrary\steamapps\common\Valheim</VALHEIM_INSTALL>
    <BEPINEX_PATH>$(AppData)\com.kesomannen.gale\valheim\profiles\test\BepInEx</BEPINEX_PATH>
    <VALHEIM_MANAGED>$(VALHEIM_INSTALL)\valheim_Data\Managed</VALHEIM_MANAGED>
    <r2ModManPath>$(AppData)\com.kesomannen.gale\valheim\profiles</r2ModManPath>
    <MOD_DEPLOYPATH>$(r2ModManPath)\test\BepInEx\plugins</MOD_DEPLOYPATH>
  </PropertyGroup>
</Project>
