<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="environment.props" Condition="Exists('environment.props')" />

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>Shipwright</AssemblyName>
    <RootNamespace>Shipwright</RootNamespace>
    <LangVersion>10.0</LangVersion>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Version>1.1.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="YamlDotNet" Version="13.1.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="BepInEx">
      <HintPath>$(BEPINEX_PATH)/core/BepInEx.dll</HintPath>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(BEPINEX_PATH)/core/0Harmony.dll</HintPath>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <Reference Include="assembly_valheim">
      <HintPath>$(VALHEIM_MANAGED)/publicized_assemblies/assembly_valheim_publicized.dll</HintPath>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <Reference Include="assembly_guiutils">
      <HintPath>$(VALHEIM_MANAGED)/publicized_assemblies/assembly_guiutils_publicized.dll</HintPath>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <Reference Include="assembly_utils">
      <HintPath>$(VALHEIM_MANAGED)/publicized_assemblies/assembly_utils_publicized.dll</HintPath>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(VALHEIM_MANAGED)/UnityEngine.dll</HintPath>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(VALHEIM_MANAGED)/UnityEngine.CoreModule.dll</HintPath>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>$(VALHEIM_MANAGED)/UnityEngine.PhysicsModule.dll</HintPath>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>$(VALHEIM_MANAGED)/UnityEngine.InputLegacyModule.dll</HintPath>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <Reference Include="UnityEngine.ParticleSystemModule">
      <HintPath>$(VALHEIM_MANAGED)/UnityEngine.ParticleSystemModule.dll</HintPath>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <Reference Include="UnityEngine.AssetBundleModule">
      <HintPath>$(VALHEIM_MANAGED)/UnityEngine.AssetBundleModule.dll</HintPath>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>$(VALHEIM_MANAGED)/UnityEngine.IMGUIModule.dll</HintPath>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>$(VALHEIM_MANAGED)/UnityEngine.UI.dll</HintPath>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>$(VALHEIM_MANAGED)/Unity.TextMeshPro.dll</HintPath>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="translations\English.yml" />
    <EmbeddedResource Include="assets\hammerbucketbundle" />
  </ItemGroup>
</Project>
